package com.gmail.stefan.backend;

import java.util.Objects;
import java.util.Random;
import java.io.Serializable;

public class Beverage implements Serializable {
	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -3387008856302472492L;
	
	private Long id;
	private String beverage = "";
	private String alc = "";
	
	public Beverage (String beverage, String alc) {
		super();
		this.id = new Random().nextLong();
		this.beverage = beverage;
		this.alc = alc;
	}
	
	public Beverage(Beverage other) {
		
		if(other== null) other = new Beverage();
		this.beverage = other.getBeverage()!=null ? other.getBeverage() : "";
		this.alc = other.getAlc()!=null ? other.getAlc() : "";
	}
	
	// getters & setters
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getBeverage() {
		return beverage;
	}

	public void setBeverage(String beverage) {
		this.beverage = beverage;
	}

	public String getAlc() {
		return alc;
	}

	public void setAlc(String alc) {
		this.alc = alc;
	}

	
	public Beverage() {
		// TODO Auto-generated constructor stub
	}

	@Override
    public String toString() {
        // Must use getters instead of direct member access,
        // to make it work with proxy objects generated by the view model
        return "Beverage{" + getId() + ":" + getBeverage() + getAlc() +'}';
    }
}